# Function to create embeddings and FAISS database

def create_embeddings():


    # Import libraries only when function runs

    import faiss
    import json
    import pickle

    from sentence_transformers import SentenceTransformer






    # Load transcript generated by Whisper

    with open(
        "transcripts/test.json",
        "r"
    ) as file:


        segments = json.load(
            file
        )







    # Store transcript text

    texts = []


    for segment in segments:


        texts.append(
            segment["text"]
        )






    print(
        "Total text chunks:",
        len(texts)
    )






    # Check empty transcript

    if len(texts) == 0:


        raise Exception(
            "Transcript is empty. No text found for embedding."
        )







    print(
        "Sample text:",
        texts[:3]
    )







    # Load embedding model

    print(
        "Loading embedding model..."
    )


    model = SentenceTransformer(
        "all-MiniLM-L6-v2"
    )







    # Save embedding model
    # So Streamlit RAG does not reload HuggingFace


    with open(
        "embedding_model.pkl",
        "wb"
    ) as file:


        pickle.dump(
            model,
            file
        )



    print(
        "Embedding model saved"
    )









    # Convert transcript text into vectors

    print(
        "Creating embeddings..."
    )


    embeddings = model.encode(
        texts
    )






    print(
        "Embedding shape:",
        embeddings.shape
    )






    # Vector size

    dimension = embeddings.shape[1]







    # Create FAISS index

    index = faiss.IndexFlatL2(
        dimension
    )






    # Add vectors

    index.add(
        embeddings
    )







    # Save FAISS database

    faiss.write_index(
        index,
        "video_index.faiss"
    )








    # Save text + timestamps

    with open(
        "metadata.json",
        "w"
    ) as file:


        json.dump(
            segments,
            file,
            indent=4
        )







    print(
        "FAISS database saved"
    )







    return {
        "vectors": index.ntotal,

        "dimension": dimension
    }