# Function to process uploaded video

def process_video(video_path):


    # Import libraries only when button is clicked

    import whisper
    import torch
    import json



    # Checking whether GPU is available or not

    print(
        "GPU:",
        torch.cuda.is_available()
    )



    # Loading Whisper model for speech recognition

    model = whisper.load_model(
        "base",
        device="cuda"
    )



    # Converting video speech into text with timestamps

    result = model.transcribe(
        video_path
    )
    
    del model

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


    # Checking what Whisper detected

    print(
        "Detected text:",
        result["text"]
    )


    print(
        "Segments found:",
        len(result["segments"])
    )



    # Empty list to store all transcript segments

    segments = []



    # Extracting start time, end time and text
    # generated by Whisper

    for segment in result["segments"]:


        segments.append(
            {
                "start": segment["start"],

                "end": segment["end"],

                "text": segment["text"]
            }
        )



    # Saving transcript into JSON file

    with open(
        "transcripts/test.json",
        "w"
    ) as file:


        json.dump(
            segments,
            file,
            indent=4
        )



    print(
        "Transcript saved successfully"
    )



    return "completed"